<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>DigitalBrain.Scripting</RootNamespace>
    <Description>Immutable file application compilation and authoring for DigitalBrain.</Description>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../DigitalBrain.Contracts/DigitalBrain.Contracts.csproj" />
    <ProjectReference Include="../DigitalBrain.Sdk/DigitalBrain.Sdk.csproj" />
    <ProjectReference Include="../../Modules/UI/DigitalBrain.Modules.UI.Contracts/DigitalBrain.Modules.UI.Contracts.csproj" />
    <ProjectReference Include="../../Modules/AI/Contracts/DigitalBrain.Modules.AI.Contracts.csproj" />
  </ItemGroup>

</Project>
